import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const app=fs.readFileSync(new URL('../web/app.js',import.meta.url),'utf8');

// Exercise the actual menu handlers with mouse, keyboard, and the boundary
// events generated by non-hover pointers. No third-party DOM package is needed.
function menus(){
  class Element {
    constructor(tag,classes=''){
      this.tag=tag;this.children=[];this.listeners={};this.attributes={};this.style={};this.dataset={};
      const values=new Set(classes.split(' ').filter(Boolean));
      this.classList={add:name=>values.add(name),remove:name=>values.delete(name),contains:name=>values.has(name)};
    }
    append(...children){for(const child of children){this.children.push(child);child.parentElement=this;}}
    matches(selector){
      if(selector==='[data-action]')return Boolean(this.dataset.action);
      const classes=[...selector.matchAll(/\.([\w-]+)/g)].map(match=>match[1]);
      const tag=/^[a-z]+/.exec(selector)?.[0];
      return classes.every(name=>this.classList.contains(name))&&(!tag||this.tag===tag)&&(!selector.includes(':not(:disabled)')||!this.disabled);
    }
    querySelectorAll(selector){
      const parts=selector.split(' '),last=parts.pop(),found=[];
      const walk=root=>{for(const child of root.children){
        if(child.matches(last)){
          let ancestor=child.parentElement,index=parts.length-1;
          while(ancestor&&index>=0){if(ancestor.matches(parts[index]))index--;ancestor=ancestor.parentElement;}
          if(index<0)found.push(child);
        }
        walk(child);
      }};
      walk(this);return found;
    }
    querySelector(selector){return this.querySelectorAll(selector)[0];}
    closest(selector){for(let node=this;node;node=node.parentElement)if(node.matches(selector))return node;}
    setAttribute(name,value){this.attributes[name]=value;}
    getBoundingClientRect(){return this.bounds??{left:4,top:50,right:339,bottom:150,width:335,height:100};}
    addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
    dispatch(name,properties={}){
      const event={target:this,stopPropagation(){this.stopped=true;},preventDefault(){this.prevented=true;},...properties};
      for(let node=this;node;node=event.stopped||name.startsWith('pointer')?undefined:node.parentElement)
        for(const fn of node.listeners[name]??[])fn(event);
      return event;
    }
    focus(){this.focused=true;}
    click(){this.dispatch('click');}
  }
  const document=new Element('document'),bar=new Element('nav','menus');document.append(bar);
  function menu(){
    const root=new Element('div','menu'),heading=new Element('button','menu-heading'),popup=new Element('div','menu-popup');
    root.append(heading,popup);bar.append(root);return {root,heading,popup};
  }
  function branch(popup){
    const root=new Element('div','menu-branch'),heading=new Element('button','submenu-heading'),submenu=new Element('div','menu-submenu'),action=new Element('button');
    action.dataset.action='open-audio';submenu.append(action);root.append(heading,submenu);popup.append(root);return {root,heading,submenu,action};
  }
  const file=menu(),help=menu(),audio=branch(file.popup),other=branch(file.popup);
  const picker=new Element('input');let pickerCalls=0;
  picker.click=()=>{pickerCalls++;};
  const sandbox={document,window:{},innerWidth:900,innerHeight:800,actions:{'open-audio':()=>picker.click()}};
  vm.runInNewContext(app.slice(app.indexOf('let hoverOpenedMenu;'),app.indexOf('// Labels, order, and values follow'))+'\n'+
    app.slice(app.indexOf("document.querySelectorAll('[data-action]').forEach"),app.indexOf("document.querySelectorAll('[data-close-dialog]')")),sandbox);
  return {document,file,help,audio,other,sandbox,get pickerCalls(){return pickerCalls;}};
}

for(const pointerType of ['touch','pen']){
  const ui=menus();ui.file.heading.click();
  // Contact with another top-level menu must not activate mouse hover switching.
  ui.help.root.dispatch('pointerenter',{pointerType});assert.ok(ui.file.root.classList.contains('open'));
  assert.equal(ui.help.root.classList.contains('open'),false);
  // A branch opens by tap; finger lift leaves it open for the next action.
  ui.audio.root.dispatch('pointerenter',{pointerType});assert.equal(ui.audio.root.classList.contains('submenu-open'),false);
  ui.audio.heading.click();ui.audio.root.dispatch('pointerleave',{pointerType});
  assert.ok(ui.audio.root.classList.contains('submenu-open'),'finger lift must not close the submenu');
  ui.other.root.dispatch('pointerenter',{pointerType});assert.ok(ui.audio.root.classList.contains('submenu-open'));
  // Test both boundary-event orderings around action activation. The picker must
  // open once per tap, synchronously, while the menu closes after selection.
  for(const leaveBeforeClick of [true,false]){
    if(!ui.file.root.classList.contains('open'))ui.file.heading.click();ui.audio.heading.click();
    ui.audio.root.dispatch('pointerenter',{pointerType});
    if(leaveBeforeClick)ui.audio.root.dispatch('pointerleave',{pointerType});
    assert.ok(ui.audio.root.classList.contains('submenu-open'),'action must remain visible until click');
    const previous=ui.pickerCalls;ui.audio.action.click();
    if(!leaveBeforeClick)ui.audio.root.dispatch('pointerleave',{pointerType});
    assert.equal(ui.pickerCalls,previous+1);assert.equal(ui.file.root.classList.contains('open'),false);
  }
}

{
  const ui=menus();ui.file.heading.click();ui.audio.root.dispatch('pointerenter',{pointerType:'mouse'});
  assert.ok(ui.audio.root.classList.contains('submenu-open'));
  ui.audio.root.dispatch('pointerleave',{pointerType:'mouse'});assert.equal(ui.audio.root.classList.contains('submenu-open'),false);
  ui.help.root.dispatch('pointerenter',{pointerType:'mouse'});assert.ok(ui.help.root.classList.contains('open'));
  ui.help.heading.click();assert.ok(ui.help.root.classList.contains('open'),'clicking a hover-opened menu keeps it open');
  ui.help.heading.click();assert.equal(ui.help.root.classList.contains('open'),false);
}

{
  const ui=menus();ui.file.heading.click();
  assert.ok(ui.audio.heading.dispatch('keydown',{key:'ArrowRight'}).prevented);
  assert.ok(ui.audio.root.classList.contains('submenu-open'));assert.ok(ui.audio.action.focused);
  ui.audio.heading.dispatch('keydown',{key:'ArrowLeft'});assert.equal(ui.audio.root.classList.contains('submenu-open'),false);
  ui.audio.heading.click();ui.document.dispatch('click');assert.equal(ui.file.root.classList.contains('open'),false);
}

// A submenu must stay reachable in the visible viewport, including when a
// mobile user has zoomed and panned without changing the layout viewport.
{
  const ui=menus();ui.file.heading.click();
  ui.audio.root.bounds={left:4,top:50};ui.audio.submenu.bounds={left:264,top:47,right:599,bottom:147,width:335,height:100};
  ui.audio.heading.bounds={top:50,bottom:74};
  ui.sandbox.innerWidth=393;ui.audio.heading.click();assert.equal(ui.audio.submenu.style.left,'50px');
  assert.equal(ui.audio.submenu.style.top,'24px','overlapping submenu must stay below its heading');
  ui.sandbox.window.visualViewport={offsetLeft:100,offsetTop:80,width:393,height:120};
  ui.audio.root.bounds={left:104,top:154};ui.audio.heading.bounds={top:154,bottom:178};
  ui.audio.submenu.bounds={left:364,top:151,right:699,bottom:251,width:335,height:100};
  ui.audio.heading.click();assert.equal(ui.audio.submenu.style.left,'50px');assert.equal(ui.audio.submenu.style.top,'-70px');
  assert.equal(ui.audio.submenu.style.maxHeight,'70px','overlapping submenu scrolls above the heading when space below is limited');
  ui.sandbox.window.visualViewport=undefined;ui.sandbox.innerWidth=900;ui.audio.heading.click();
  assert.equal(ui.audio.submenu.style.left,'100%');assert.equal(ui.audio.submenu.style.top,'-3px');assert.equal(ui.audio.submenu.style.maxHeight,'');
}

console.log('Passed: touch/pen submenu persistence, synchronous playback picker, viewport placement, mouse hover, keyboard, and outside dismissal.');
